### ISSUE TITLE
Can't use FactionsPerms/FactionsFramework

### ISSUE THREAD

**Issue by C0LiSii0N** [MarkehMe/FactionsFramework#16]
When I start my server I alway get this, running Spigot 1.8.8

```
 [Server thread/ERROR]: Could not load 'plugins/FactionsFramework.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/markeh/factionsframework/FactionsFramework : Unsupported major.minor version 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_111]
Caused by: java.lang.UnsupportedClassVersionError: me/markeh/factionsframework/FactionsFramework : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_111]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803) ~[?:1.7.0_111]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_111]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_111]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_111]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_111]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_111]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_111]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_111]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_111]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_111]
	at java.lang.Class.forName(Class.java:278) ~[?:1.7.0_111]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	... 6 more
```

**Comment by MarkehMe** [comment]
Please upgrade Java 😃  FactionsFramework is build against Java 8. 

Here is [a guide](https://techhelpkb.com/how-to-update-java-on-your-computer/) I've found online for you.
