### ISSUE TITLE
Error spam in console

### ISSUE THREAD

**Issue by Maymity** [MarkehMe/FactionsFramework#25]
Quick, [18.07.17 15:08]
[06:40:27] [Server thread/ERROR]: Could not pass event LandClaimEvent to FactionsFramework v1.2.0
org.bukkit.event.EventException
  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
  at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
  at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
  at com.massivecraft.factions.zcore.persist.MemoryFPlayer.attemptClaim(MemoryFPlayer.java:801) [Factions.jar:?]
  at com.massivecraft.factions.cmd.CmdClaim.perform(CmdClaim.java:43) [Factions.jar:?]
  at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) [Factions.jar:?]
  at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) [Factions.jar:?]
  at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) [Factions.jar:?]
  at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) [Factions.jar:?]
  at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) [Factions.jar:?]
  at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:299) [Factions.jar:?]
  at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:262) [Factions.jar:?]
  at com.massivecraft.factions.P.handleCommand(P.java:189) [Factions.jar:?]
  at com.massivecraft.factions.P.onCommand(P.java:200) [Factions.jar:?]
  at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
  at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
  at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
  at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
  at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
  at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
  at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
  at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
  at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
  at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
  at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
  at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
  at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
  at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
  at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassCastException

**Comment by markhughes** [comment]
Sorry, FactionsUUID API is broken and no longer supported.
