### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Uranusak** [MarkehMe/FactionsFramework#26]
Spigot 1.12.2-R0.1
Factions 2.13.2
FreshWilderness v1.5.0
Factions Framework 1.2.0

```
Could not pass event BlockBreakEvent to FreshWilderness v1.5.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-93e20b3-31d3159]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-93e20b3-31d3159]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:290) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:123) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:875) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NoSuchMethodError: com.massivecraft.factions.entity.FactionColl.get(Ljava/lang/Object;)Lcom/massivecraft/factions/entity/Faction;
        at me.markeh.factionsframework.layer.layer_2_8_6.Faction_2_8_6.<init>(Faction_2_8_6.java:31) ~[?:?]
        at me.markeh.factionsframework.layer.layer_2_8_6.Factions_2_8_6.get(Factions_2_8_6.java:36) ~[?:?]
        at me.markeh.factionsframework.layer.layer_2_8_6.Factions_2_8_6.getAt(Factions_2_8_6.java:59) ~[?:?]
        at me.markeh.factionsframework.entities.Factions.getFactionAt(Factions.java:95) ~[?:?]
        at net.redstoneore.freshwilderness.integrations.factions.FactionsEngine.isNone(FactionsEngine.java:51) ~[?:?]
        at net.redstoneore.freshwilderness.integrations.factions.FactionsEngine.shouldLogAt(FactionsEngine.java:30) ~[?:?]
        at net.redstoneore.freshwilderness.integrations.Integrations.shouldLogAt(Integrations.java:85) ~[?:?]
        at net.redstoneore.freshwilderness.FreshWilderness.logChunk(FreshWilderness.java:127) ~[?:?]
        at net.redstoneore.freshwilderness.FreshWilderness.onBlockBreak(FreshWilderness.java:123) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-93e20b3-31d3159]
        ... 17 more

```

**Comment by markhughes** [comment]
Duplicate #24
